defaults:
  create:
    force: true
  link:
    create_parent_dirs: true

steps:
  - brew:
      formula:
        # Shell tools
        - fzf
        - shellcheck
        - shfmt
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
        - zsh-vi-mode
  - link:
      - ~/.zshrc: zshrc
      - ~/.zshenv: zshenv
      - ~/.zshrc-imports/.aliases: zshrc-imports/aliases
      - ~/.p10k.zsh: p10k.zsh
      - ~/.oh-my-zsh/custom/plugins/_bazel: custom/plugins/_bazel
      - ~/.oh-my-zsh/custom/plugins/arcanist-tw: custom/plugins/arcanist-tw
  - create:
      - ~/.oh-my-zsh/custom/plugins/alias-tips
      - ~/.oh-my-zsh/custom/themes/powerlevel10k
  - exec:
      - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
      - git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips
