defaults:
  create:
    force: true
  exec:
    echo: true
  brew:
    force_casks: true
  link:
    force: true
    relink: true

steps:
  - brew:
      formula:
        # This is bazelisk on mac, bazel on linux
        - bazel
